// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isrihfysewgfszxfdcwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzcmloZnlzZXdnZnN6eGZkY3d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTk0OTAsImV4cCI6MjA2NDc3NTQ5MH0.Z4YSqjZptgbWURFxgoKIvHC42gEr6iL6gAXBCWaXUd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);